name: Deploy to Cloud Foundry
on:
  push:
    branches:
    - main
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: node:14.16
      env:
        NODE_ENV: development
      ports:
        - 80
      volumes:
        - my_docker_volume:/volume_mount
      options: --cpus 1
    steps:
      - name: Check for dockerenv file
        run: (ls /.dockerenv && echo Found dockerenv) || (echo No dockerenv)


  # build:
  #   runs-on: ${{ matrix.os }}
  #   strategy:
  #     matrix:
  #       node-version: [16.x]
  #       os: [ubuntu-latest]   
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3
      
  #     - name: Login to Docker Hub
  #       uses: docker/login-action@v2
  #       with:
  #         username: ${{ secrets.DOCKERHUB_USERNAME }}
  #         password: ${{ secrets.DOCKERHUB_TOKEN }}

  #     - name: CF Login
  #       uses: ppiper/cf-cli
  #       with:
  #         CX_INFRA_IT_CF_USERNAME: ${{ secrets.CF_USERNAME }}
  #         CX_INFRA_IT_CF_PASSWORD: ${{ secrets.CF_PASSWORD }} 